
name: Deploy to Kubernetes

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted  # Self-hosted runner

    steps:
    
     
        

      # Deploy to Kubernetes
      - name: Deploy to k8s
        run: |
      
        
 
          


           
           kubectl apply -f deployment.yml
           kubectl rollout status deployment/nginx-deployment
           kubectl get pods | grep nginx
